# Utiliza la imagen base de .NET 8 SDK
FROM mcr.microsoft.com/dotnet/sdk:8.0

# Establece el directorio de trabajo en /app
WORKDIR /app

# Establece el punto de entrada para ejecutar el proyecto específico
ENTRYPOINT ["dotnet", "run", "--project", "WebApi"]

